version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/supply-0.0.1-SNAPSHOT.jar
  discard-paths: yes